import React from 'react';
import '../index.css';

const smallImage = require("../../../assets/smashdown-thumbnail.png")
const largeImage = require("../../../assets/smashdown.png")

const SmashDown = () => {
    return (
        <main className="project-container">
                <h1 className="project-title">Smash Down</h1>
                <p className="project-description">
                    The client wanted a webpage that allowed them to track characters and scores for a game that they play. I decided to use a layout
                    similar to the one found in the game.
                </p>
                <p className="project-description">
                    I built the page using plain HTML and CSS plus JavaScript with jQuery. The  character portraits are generated by a
                    for loop that creates each image element and appends them to a div. I used the flex display in CSS to get the layout, which is
                    responsive adjusting the images for different screens sizes.
                </p>
                <p className="project-description">
                    For this webpage I decided to try out jQuery, I liked the ease of selecting DOM elements and the improved readability of code. 
                    The feature that I found most useful was the built in iterator which made for cleaner code. 
                </p>
                <p className="project-description">
                    I wrote a suit of tests for the code using the Jest library, mainly running functions on mock 
                    elements to check the correct actions are carried out on them. This project also used NPM, Webpack, Babel, Prettier and ESLint.
                </p>
                <a className="project-link" href="https://smash-down.neocities.org/">Visit the site</a>
                <a className="project-link" href="https://github.com/jakehowlett93/smash-down">Visit the repository.</a>
                <img 
                    className="project-image" 
                    src={smallImage} 
                    srcSet={`${smallImage} 424w, ${largeImage} 1149w`}
                    sizes="(max-width: 600px) 80vw"
                    alt=""
                />
        </main>
            
    )
}

export default SmashDown;